# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11rvUUHElFd0wR2HsoVo0ERfTTTVxSoWR

taller 1
"""

Identificacion=int(input('Identidicación:'))
Nombre=str(input('Nombres:'))
Apellido=str(input('Apellidos:'))
Direccion=str(input('Dirección:'))
Telefono=int(input('Teléfono:'))
Edad=int(input('Edad:'))
Estado_civil=str(input('Estado civil:'))
Numero_dehijos=int(input('Numero de Hijos:'))
Estatura=float(input('Estatura:'))
Fecha_de_Contratacion=(int(input('Dia:')),(int(input('Mes:'))),(int(input('Año:'))))
Sueldo=int(input('Sueldo Básico:'))
Dias_lab=int(input('Dias Laborados: '))
print('Identifación:',Identificacion)
print('Nombres:',Nombre)
print('Apellidos:',Apellido)
print('Dirección:',Direccion)
print('Telefono:',Telefono)
print('Edad:',Edad)
print('Estado Civil:',Estado_civil)
print('Número de hijos:',Numero_dehijos) 
print('Estatura:',Estatura)
print('Fecha de Contratación')
print('Sueldo:',Sueldo)
print('Días laborados:',Dias_lab)

"""taller 2"""

compra = float(input("¿de cuanto fue el total de la compra?:" )

iva = compra * 0.15 
total = compra + iva

print("EL IVA es= {} y el total a pagar es= {}".format(iva, total))

sueldo = float(input("sueldo"))
venta1 =float(input("venta 1"))
venta2 =float(input("venta 2"))
venta3 =float(input("venta 3"))
comision  = (venta1+venta2+venta3)* 0.10
print ("el sueldo del trabajador es: $",sueldo) 
print("la comision del mes por las 3 ventas es: $",comision)
print("el sueldo total es: $", sueldo + comision)

calificacion1 = float(input("Digite la calificación 1: "))
calificacion2 = float(input("Digite la calificación 2: "))
calificacion3 = float(input("Digite la calificación 3: "))

prom = round((calificacion1 + calificacion2 + calificacion3)/3.5)

print(f"Calificacion final es= {prom}")

mujeres = int(input("numero de mujeres"))
hombres = int(input("numero de hombres"))

total = mujeres + hombres

print ("el porcentaje de mujeres es:  ",(mujeres/total)*100,"%")
print ("el porcentaje de hombres  es: ",(hombres/total)*100,"%")

"""taller 3"""

Identificacion=int(input('Identidicación:'))
#print('Identifación:',Identificacion)
Nombre=str(input('Nombres:'))
#print('Nombres:',Nombre)
Apellido=str(input('Apellidos:'))
#print('Apellidos:',Apellido)
Direccion=str(input('Dirección:'))
#print('Dirección:',Direccion)
Telefono=int(input('Teléfono:'))
#print('Telefono:',Telefono)
Edad=int(input('Edad:'))
if Edad >= 55:
  print("cuenta con la edad para el bono")
else:
  print("no cuenta con la edad para el bono")
Estado_civil=str(input('Estado civil:')) 

if Estado_civil != "soltero":
  print("paseo familiar")
else:
    print("No apto para paseo familiar")
    
    Numero_dehijos=int(input('Numero de Hijos:'))
#print('Número de hijos:',Numero_dehijos)
Estatura=float(input('Estatura:'))
#print('Estatura:',Estatura)
Fecha_de_Contratacion=(int(input('Dia:')),(int(input('Mes:'))),(int(input('Año:'))))
#print('Fecha de Contratación')
Sueldo=int(input('Sueldo Básico:'))
if  1000000 == 1500000:
  print ("comision del 2%")
elif Sueldo > 1500001 == 200000:
  print ("comision del 5%")
elif Sueldo == 200000:
    print ("comision del 5%")
else:
      print("no tiene comision")

num = int(input("Digite el número de la tabla de multiplicar: "))

for i in range(11):
  print(i, " x ", num, " = ", num * i)

# variables acumuladoras
acu = 0

for i in range(0,20,2):
  # print(i)
  acu = acu + i
print(f"El total de la suma de los números pares del 0-100 es= {acu}")

"""taller 4."""

#numero = input("pares:")
for w in range (0,100,2):
    print(w,)

resp = "aplica"

while resp == "aplica" or "si" or "si aplica" or "cuanto es el bono":

 
    sueldo = int (input("sueldo: "))

    if sueldo <= 655000:

        Sueldo = sueldo

        total = Sueldo * 0.04

        print("tiene bonificacion del 4% sobre el sueldo real el cual es de: $",total, "el sueldo total es de: $", Sueldo + total  )

        resp = input("¿Desea ejecutar nuevamente?")

    else:

        print("no tiene bono, el total a pagar es: $",sueldo)

        resp = input("¿Desea ejecutar nuevamente?")

"""taller 5"""

def suma (mujeres,hombres):
  res = mujeres + hombres
  print(f"el resultado es ={res}",)
mujeres = int(input("numero de mujeres"))
hombres = int(input("numero de hombres"))
#print(res)
suma(hombres,mujeres)

total = mujeres + hombres

print ("el porcentaje de mujeres es:  ",(mujeres/total)*100,"%")
print ("el porcentaje de hombres  es: ",(hombres/total)*100,"%")